### ISSUE TITLE
events should limit user inputs

### ISSUE THREAD

**Issue by silent2600** [juanparati/MooUpload#16]
hi,

I see there are some events: 
   onAddFiles: function(){},
    onBeforeUpload: function(){},
    onFileDelete: function(fileindex){},
    onFileUpload: function(fileindex, response){},
    onFileUploadError: function(fileindex, response){},
    onFinishUpload: function(){},
    onSelect: function(){},
    onSelectError: function(error, filename, filesize){}

what I want is the events can control the js progress:
for example: 
when user already added 5 files, onAddFiles() can prevent adding more files,
anyother way is user selected 10 files, onBeforeUpload() also can prevent uploading any file.

also the "accept" option seems not work in HTML5, only see some code on it for flash.

thanks!

**Comment by juanparati** [comment]
I think that the best way is to limit the max file number using a "maxfiles" param, and use onSelectError as event for this error type.

I will include this new option the next minor version.

"Accept" option, only works partially in Firefox 5+ (Try with 'image/*'), because "accept" specification is already a draft (See: http://dev.w3.org/html5/markup/input.file.html)

**Comment by juanparati** [comment]
New version contain a maxfiles feature.
