### ISSUE TITLE
Test : HTML5 doesn't work

### ISSUE THREAD

**Issue by lspg** [juanparati/MooUpload#2]
Hi,

i just gave it a try, flash upload works well but i cannot make the html5 works. Any advice ?

**Comment by juanparati** [comment]
What web browser are you using?

**Comment by lspg** [comment]
Chrome 12.0.742.100

**Comment by juanparati** [comment]
I have updated to Chrome 12.0.742.100 and I seen that works!

I have reduce the default blocksize from 1024000 to 512000 bytes because if you try to upload some file using the HTML5, you can feel like the upload is freeze, specially if you have a slow internet connection.

You can change the default blocksize using the option blocksize (I recommend you for slow connections 102400 bytes)

Anyway, If the problem persist can you give more information about the problem like the file size that you try to upload, if you have installed any Chrome extensions, are you using a commercial firewall or console error if exists.

I will appreciate more information about this problem if exists.

**Comment by juanparati** [comment]
Hmmm, Have you try with other web browsers??

Maybe your server configuration have a limitation for post more than 1024000 bytes

I have read that you have problems also with Jquery-File-Upload:
https://github.com/blueimp/jQuery-File-Upload/issues/377#issuecomment-1374742
