### ISSUE TITLE
Filename specification

### ISSUE THREAD

**Issue by lorenzos** [juanparati/MooUpload#23]
`Mooupload::upload()` should have an extra optional parameter to specify filename for the uploaded file. This, together with `$destpath`, let us specify the exact path where the file should be written. 

This way, we can implement every file writing logic we want (avoid overwriting? rename in case of file already exists? etc) before calling `Mooupload::upload()` in `upload.php`.

**Comment by juanparati** [comment]
I think that is a reasonable improvement. I am working on that!

**Comment by juanparati** [comment]
Implemented!  

However requires that for the HTML5 when you move the upload file to the destination path, you should use the $file_prefix variable. The reason is that HTML5 can upload a lot of files at the same time, and internally the files are uploaded with a unique prefix that avoids that two different files with the same name could be overwrote.

HTML 4 and Flash don´t have this problem because they using HTML 4 method, and the file upload is not synchronous.

**Comment by lorenzos** [comment]
Cool ;)
