### ISSUE TITLE
IE 7/8 issue - add file button

### ISSUE THREAD

**Issue by kolin1979** [juanparati/MooUpload#5]
Hi,

firstly thanks for the upload, it's just what i needed.
One issue ive found, and unfortunately i cant eloborate on where it actually happens in the code, is that in IE 7/8, when the page is first loaded, and the method is set to 'flash' the button 'addFile' remains as a button and does not change into the flash object, and therefore there is no functionality. However if i refresh the page, the button works as expected.

this happens on the mooForge demo as well as my own integration.

many thanks again.

Colin

**Comment by kolin1979** [comment]
on further inspection, it seems that the 'load' callback from the :
this.flashobj = new Swiff(this.options.flash.movie
line is not being called on the first load. However it gets called when the page is refreshed.

**Comment by juanparati** [comment]
Hi Kolin!

Thanks for the bug report. 

The problem is that something strange occurs when IE save the flash files in the cache. I think that is an IE security issue for prevent the remote execution of local Flash files that use fileReference.

Fortunately I found a solution (thanks to this post: http://www.kirupa.com/forum/showthread.php?297008-Flash-IE-cache-error). So now MooUpload will add a random param to the flash script path, and in this way IE always is forcing the download of a new copy of the flash script with the normal execution privileges.

You can download the fixed version from the github repository. Also I have upload the fix to the demo page.

**Comment by kolin1979** [comment]
thanks for that juan,

i thought i'd fixed it myself by making the references to 'this.flashobj', instead of 'this.flashobj.toElement()' which IE seemed to be disliking.
and then adding :
this.flashobj = document.id(this.flashobj.id);
immediately after the creation of the swiff object.
